pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'g++ -o hello_exec main.cpp'
            }
        }

        stage('Test') {
            steps {
                sh './hello_exec'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying application...'
            }
        }
    }

    post {
        failure {
            echo "Pipeline failed!"
        }
    }
}
